### ISSUE TITLE
pmerge -avuDN @world returns resolution failure

### ISSUE THREAD

**Issue by B83C** [pkgcore/pkgcore#373] opened 2022-10-23 03:59 UTC
Pkgcore merge doesn't seem to work on my gentoo somehow

```
b83c@t14s ~ $ doas pmerge -aD @world
 * Resolving...
!!! resolution failed
!!! request ( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && media-libs/libva ), mode none
!!! trying media-libs/libva-2.15.0
!!!   request >=dev-util/meson-0.62.2, mode bdepend
!!!   trying dev-util/meson-0.62.2
!!!     request >=dev-lang/python-3.10.4:3.10, mode rdepend
!!!     trying dev-lang/python-3.10.8
!!!       request sys-apps/util-linux:0/0=, mode rdepend
!!!       trying sys-apps/util-linux-2.37.4
!!!         request virtual/libcrypt:0/2=, mode rdepend
!!!         trying virtual/libcrypt-2
!!!           request sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)], mode rdepend
!!!           trying sys-libs/libxcrypt-4.4.28-r1
!!!             request sys-libs/glibc[-crypt(+)], mode rdepend
!!!             removing choices involving sys-libs/glibc[-crypt(+)]
!!!           removing choices involving sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)]
!!!         removing choices involving virtual/libcrypt:0/2=
!!!       trying sys-apps/util-linux-2.37.4
!!!         request virtual/libcrypt:=, mode depend
!!!         trying virtual/libcrypt-2
!!!           request sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)], mode rdepend
!!!           removing choices involving sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)]
!!!         removing choices involving virtual/libcrypt:=
!!!       removing choices involving sys-apps/util-linux:0/0=
!!!     trying dev-lang/python-3.10.8
!!!       request sys-apps/util-linux:=, mode depend
!!!       trying sys-apps/util-linux-2.37.4
!!!         request virtual/libcrypt:0/2=, mode rdepend
!!!         trying virtual/libcrypt-2
!!!           request sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)], mode rdepend
!!!           removing choices involving sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)]
!!!         removing choices involving virtual/libcrypt:0/2=
!!!       trying sys-apps/util-linux-2.37.4
!!!         request virtual/libcrypt:=, mode depend
!!!         trying virtual/libcrypt-2
!!!           request sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)], mode rdepend
!!!           removing choices involving sys-libs/libxcrypt[abi_x86_32(-),abi_x86_64(-),system(-)]
!!!         removing choices involving virtual/libcrypt:=
!!!       removing choices involving sys-apps/util-linux:=
!!!     removing choices involving >=dev-lang/python-3.10.4:3.10
!!!   removing choices involving >=dev-util/meson-0.62.2

Failures encountered:
!!! failed '( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && media-libs/libva )'
potentials:
repo gentoo: [ ebuild src: media-libs/libva-2.14.0, ebuild src: media-libs/libva-2.15.0, ebuild src: media-libs/libva-2.16.0, ebuild src: media-libs/libva-9999 ]
b83c@t14s ~ $ 
```

The error shows up whenever I try to update packages.

**Comment by arthurzam** [comment] 2022-10-23 19:19
It looks like you have an issue with `glibc[crypt]` flag (I don't know if `-crypt` or `crypt`). Maybe this one will help? https://wiki.gentoo.org/wiki/User:Sam/Portage_help/Circular_dependencies#Python_and_libcrypt

Also note that it would be better for you to use `portage` for most cases. I'm sorry to say that pkgcore as package manager isn't really maintained by me. Currently I see pkgcore as more of a infrastructure for pkgcheck & pkgdev. It also doesn't support newer portage features.

I also don't know what info ask from you to understand what is going on to reproduce it.

**Comment by thesamesam** [comment] 2022-10-23 19:33
As far as I know, pkgcore doesn't support subslot rebuilds, which is why it gets jammed up on libxcrypt.

**Comment by thesamesam** [comment] 2022-12-22 03:49
Ah, https://github.com/pkgcore/pkgcore/pull/381 will fix this, but I have no idea what resolution it'll provide for a system which hasn't yet performed the libxcrypt rebuilds.

**Comment by thesamesam** [comment] 2022-12-25 17:57
#381 is merged.

**Closed by thesamesam** 2022-12-25 17:57 UTC
