### ISSUE TITLE
keywording tool

### ISSUE THREAD

**Issue by chutz** [pkgcore/pkgcore#274] opened 2019-11-30 18:16 UTC
It would be *very* useful when filing keyword requests to have a tool that one could give it a package atom, and a list of target keywords and it would print what packages needs what keywords to achieve this.

**Comment by radhermit** [comment] 2019-11-30 19:03
This is a duplicate of https://github.com/pkgcore/pkgcore/issues/72.

**Closed by radhermit** 2019-11-30 19:03 UTC
Labels: duplicate
