### ISSUE TITLE
Support config directories

### ISSUE THREAD

**Issue by suhr** [pkgcore/pkgcore#173] opened 2016-02-06 13:58 UTC
make.profile, package.mask{unmask,keyword}, etc.

Related issue: https://github.com/pkgcore/pkgcore/issues/78.

**Comment by radhermit** [comment] 2016-02-06 16:15
I'm somewhat sure the only one missing is make.profile.

**Comment by radhermit** [comment] 2016-03-12 03:05
Closing this since it's mostly a duplicate of #78, unless you can come up with config dirs besides make.profile that are unsupported and are specc-ed that they should be.

**Closed by radhermit** 2016-03-12 03:05 UTC
Labels: duplicate
